# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    
  pull_request:
    types:
      - closed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Script
      run: |
        export PR_NUMBER=1 && export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} && python compass-monorepo-script.py
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo The PR was merged
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Script
      run: |
        export PR_NUMBER=${{ github.event.pull_request.number }} && export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} python compass-monorepo-script.py
    - name: Archive results
      uses: actions/upload-artifact@v4
      with:
        name: metrics-report
        path: deployment_metrics.json