# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
    inputs:
      pull_request_to_test:
        description: 'Pull Request Id to Test'
        required: true
        default: '1'
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Script
      env: 
        PR_NUMBER: ${{ github.event.inputs.pull_request_to_test }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USER_EMAIL: ${{ secrets.USER_EMAIL}}
        USER_API_TOKEN: ${{ secrets.USER_API_TOKEN}}
        ATLASSIAN_SITE:  ${{ secrets.ATLASSIAN_SITE}}
      run: |
         python compass-monorepo-script.py
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo The PR was merged
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Script
      env: 
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USER_EMAIL: ${{ secrets.USER_EMAIL}}
        USER_API_TOKEN: ${{ secrets.USER_API_TOKEN}}
        ATLASSIAN_SITE:  ${{ secrets.ATLASSIAN_SITE}}
      run: |
         python compass-monorepo-script.py
    - name: Archive results
      uses: actions/upload-artifact@v4
      with:
        name: metrics-report
        path: deployment_metrics.json
